name: CI

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
    name: Tests (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit and CLI tests
        run: go test -v ./...

  build-matrix:
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build with Go (matrix)
        shell: bash
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export CGO_ENABLED=0
          mkdir -p bin
          OUT=bin/passgen
          if [[ "$GOOS" == "windows" ]]; then OUT=bin/passgen.exe; fi
          go build -o "$OUT" ./